"""empty message

Revision ID: 0d4f56117985
Revises: ffdc0a98111c
Create Date: 2021-12-14 15:28:01.770570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4f56117985'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=250), nullable=False))
    op.add_column('users', sa.Column('photo_URL', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('photo_s3Name', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'photo_s3Name')
    op.drop_column('users', 'photo_URL')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
