"""empty message

Revision ID: 57edc1ea0e84
Revises: 66804a600d40
Create Date: 2021-12-18 17:57:12.964801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57edc1ea0e84'
down_revision = '66804a600d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'duration')
    op.drop_column('users', 'photo_s3Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_s3Name', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
