"""empty message

Revision ID: 66804a600d40
Revises: 253d3fdee8bc
Create Date: 2021-12-15 09:47:57.009011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66804a600d40'
down_revision = '253d3fdee8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('song_s3Name', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'song_s3Name')
    # ### end Alembic commands ###
