"""empty message

Revision ID: cdb0a0303920
Revises: 4d6cb440ee9c
Create Date: 2021-12-14 16:59:58.798056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb0a0303920'
down_revision = '4d6cb440ee9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('coverPhoto_URL', sa.String(length=2000), nullable=True),
    sa.Column('coverPhoto_s3Name', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('song_URL', sa.String(length=2000), nullable=False),
    sa.Column('song_s3Name', sa.String(length=2000), nullable=False),
    sa.Column('album', sa.String(length=250), nullable=False),
    sa.Column('artist', sa.String(length=250), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('albumCover_URL', sa.String(length=2000), nullable=True),
    sa.Column('albumCover_s3Name', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('playlists')
    # ### end Alembic commands ###
