"""empty message

Revision ID: 7edf34aa1885
Revises: 57edc1ea0e84
Create Date: 2021-12-18 17:58:13.564896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edf34aa1885'
down_revision = '57edc1ea0e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('songId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['songId'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('songs', sa.Column('duration', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('photo_s3Name', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_s3Name')
    op.drop_column('songs', 'duration')
    op.drop_table('likes')
    # ### end Alembic commands ###
