"""empty message

Revision ID: 52027a6d2c2c
Revises: 322309e9d8da
Create Date: 2023-12-09 14:42:36.294633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52027a6d2c2c'
down_revision = '322309e9d8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'trigger_upgrade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('trigger_upgrade', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
